### ISSUE TITLE
Add pulse audio

### ISSUE THREAD

**Issue by rossdargan** [rhasspy/wyoming-snd-external#5]
I'm just getting started with this but really try and run everything in Docker just to make it easier to move to new devices if I ever had to. I've managed to get this working great in Docker, but without pulse audio I'm finding it pretty limited. 

I see there was a PR here: https://github.com/rhasspy/wyoming-snd-external/pull/4 to add it which was closed. Is there any chance of getting this added in, or should I look at creating my own Docker image for it?

**Comment by synesthesiam** [comment]
This repo supports any external program, so use `paplay` to specifically target PulseAudio.
